services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: kanbandb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
  server:
    build: server/
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://root:root@db:5432/kanbandb?schema=public
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
  web:
    build: web/
    depends_on:
      - server
    ports:
      - 4200:4200
    volumes:
      - ./web:/web
