version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kanban_postgres
    restart: always
    environment:
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban123
      POSTGRES_DB: kanban_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
